### ISSUE TITLE
Vehicles edit form is not working as it should

### ISSUE THREAD

**Issue by Em-Ant** [Em-Ant/fcc-options-app#8] opened 2016-04-07 20:20 UTC
After editing a vehicle, if you edit that vehicle again the form shows the initial data (i.e. the vehicle before the first edit), not the current (edited) vehicle attributes.
![screenshot - 07042016 - 22 09 15](https://cloud.githubusercontent.com/assets/12955734/14365537/8f905420-fd0e-11e5-91d7-0f76436a927c.png)

The first vehicle has been updated to `{name: My minivan 4, fixedSeats: 9}`, then set in edit mode again. The form shows the previus data. The back-end data updates correctly.

**Comment by paycoguy** [comment] 2016-04-07 20:52
@Em-Ant This is a duplicate of #5 .  The same issue also happens on the consumer edit form.

**Comment by paycoguy** [comment] 2016-04-08 00:12
@Em-Ant I have fixed this on the vehicle form.  I also fixed this bug on the consumer form.  I have tested the changes on the consumer form and it looks like it works properly.  Can you review 68ff0525a7cb0999190ff1858cb4d40cdedbeaf2?  Let me know if it looks good, and I will close this issue.

**Closed** 2016-04-08 17:20 UTC
Labels: duplicate
